"""
This model describes a configuration selection optimization problem (discrete) for a 
flowsheet optimization of a drug substance manufacturing process described in [1]. 
The optimized configuration can then be implemented in a flowsheet simulator to be 
further optimized on the operational level. The manufacturing process consists of 5 
unit operations: reaction 1, reaction 2, vaporization, crystallization, and filtration. 
The model considers alternative unit selections for some unit operations: three choices 
for each reaction (PFR, CSTR, batch) and four choices for crystallization (1, 2, 3 
continuous MSMPR in series, batch). The model incorporates logical constraints such as 
the selection of a single unit for each operation, the selection of a hold tank if a 
batch process is selected following a continuous process, and flow conservation at each 
disjunction. The objective function for discrete optimization is to minimize capital cost. 
The model is formulated as an IP problem with disjunctive constraints and solved using Gurobi.

Additionally, an iterative process of adding an integer cut is implemented to find all 
feasible solutions to the problem. The integer cut is generated by adding a constraint 
that eliminates the current solution from the feasible region. The model is solved 
iteratively until no more feasible solutions are found.

References:
    [1] Daniel Casas-Orozco, Daniel J. Laky, Vivian Wang, Mesfin Abdi, Xin Feng, 
        Erin Wood, Gintaras V. Reklaitis, and Zoltan K. Nagy. Techno-economic analysis 
        of dynamic, end-to-end optimal pharmaceutical campaign manufacturing using pharmapy. 
        AIChE Journal, 69, 9, 2023. ISSN 15475905. doi: 10.1002/aic.18142.
    [2] Daniel J. Laky, Daniel Casas-Orozco, Carl D. Laird, Gintaras V. Reklaitis, 
        and Zoltan K. Nagy. Simulation-optimization framework for the digital design 
        of pharmaceutical processes using pyomo and pharmapy. Industrial and Engineering 
        Chemistry Research, 61: 16128–16140, 11 2022. ISSN 15205045. 
        https://pubs.acs.org/doi/abs/10.1021/acs.iecr.2c01636.
    [3] Barhate Y, Laky DJ, Casas-Orozco D, Reklaitis GV, Nagy ZK. Hybrid rule-based and 
        optimization-driven framework for the synthesis of end-to-end optimal pharmaceutical processes. 
        AIChE J. 2025;e18888. doi:10.1002/aic.18888.
"""

import pyomo.environ as pyo
import pandas as pd
from typing import Dict, List, Optional
from pathlib import Path
import json

# Import common functions
try:
    from ds_mfg_utils import (
        import_data, 
        read_sim_data,
        export_to_mps,
    )
except ImportError:
    # Fallback if common module is not available
    print("Warning: ds_mfg_common module not found. Using local implementations.")
    from ds_mfg_utils import *


class PyomoModel:
    """
    Pyomo model for flowsheet optimization of pharmaceutical manufacturing processes.
    
    This class encapsulates the complete optimization model including data import,
    model building, and solution methods.
    """
    
    def __init__(self, file_path: str, total_flow: float = 1.0):
        """
        Initialize the PyomoModel.
        
        Parameters
        ----------
        file_path : str
            Path to the CSV file containing flowsheet data.
        total_flow : float, optional
            Total flow in the network. Default is 1.0.
        """
        self.file_path = file_path
        self.total_flow = total_flow
        self.data = import_data(file_path)
        self.model = self.build_pyomo_model(*self.data, total_flow=total_flow)
    
    def build_pyomo_model(self, flow_network: Dict, flow_cost: Dict, disj: Dict, 
                         flow_with_uo: List, uo_keys: Dict, total_flow: float = 1.0) -> pyo.ConcreteModel:
        """
        Build the Pyomo optimization model.
        
        Parameters
        ----------
        flow_network : dict
            Dictionary containing flowsheet data organized by flow.
        flow_cost : dict
            Dictionary containing the cost of each flow.
        disj : dict
            Dictionary containing the disjunctions in the network.
        flow_with_uo : list
            List of flows with associated unit operations.
        uo_keys : dict
            Dictionary containing the unit operations associated with each flow.
        total_flow : float, optional
            Total flow in the network. Default is 1.0.
            
        Returns
        -------
        pyomo.environ.ConcreteModel
            The complete Pyomo optimization model.
        """
        flows = list(flow_network.keys())
        nodes = list(set(sum(flow_network.values(), ())))
        nodes.sort()
        
        # Define the source and sink nodes (assumed to be the first and last nodes)
        source_node = nodes[0]
        sink_node = nodes[-1]
        
        # Define the pyomo model
        model = pyo.ConcreteModel(doc="flowsheet optimization model")
        
        # Sets
        model.flows = pyo.Set(initialize=flows, doc="flows in the network")
        model.nodes = pyo.Set(initialize=nodes, doc="nodes in the network")
        
        # Decision Variables
        model.f = pyo.Var(
            model.flows, domain=pyo.Binary, doc="flow binary decision on each edge"
        )
        
        # Parameters
        model.fcost = pyo.Param(
            model.flows, initialize=flow_cost, doc="cost of each flow", mutable=True
        )
        
        # Objective Function (minimize cost)
        model.capex = pyo.Objective(
            expr=sum(model.f[f] * model.fcost[f] for f in model.flows),
            sense=pyo.minimize,
            doc="capital cost",
        )
        
        # Constraints
        # Flow Conservation Constraints
        def flow_conservation_rule(model, node):
            inflow = sum(
                model.f[flow] for flow in model.flows if flow_network[flow][1] == node
            )
            outflow = sum(
                model.f[flow] for flow in model.flows if flow_network[flow][0] == node
            )
            if node == source_node:
                return outflow * total_flow == total_flow  # source node
            elif node == sink_node:
                return inflow * total_flow == total_flow  # sink node
            else:
                return inflow == outflow  # intermediate nodes
        
        model.flow_conservation = pyo.Constraint(
            model.nodes,
            rule=flow_conservation_rule,
            doc="flow conservation constraints",
        )
        
        # Continuous to Batch Constraint
        # If going from continuous process to batch process, a hold tank is added to the flowsheet
        model.continuous_to_batch = pyo.ConstraintList(
            doc="continuous to batch constraints"
        )
        
        # R01 -> R02 process
        model.continuous_to_batch.add(
            (1 - model.f["f01"]) + (1 - model.f["f10"]) + model.f["f06"] >= 1
        )
        model.continuous_to_batch.add(
            (1 - model.f["f02"]) + (1 - model.f["f10"]) + model.f["f06"] >= 1
        )
        model.continuous_to_batch.add(
            (1 - model.f["f03"]) + (1 - model.f["f10"]) + (1 - model.f["f06"]) >= 1
        )
        model.continuous_to_batch.add(
            model.f["f01"] + model.f["f02"] + model.f["f05"] >= 1
        )
        model.continuous_to_batch.add(model.f["f10"] + model.f["f05"] >= 1)
        
        # Crystallizer (CR) process
        def cr_rule(model, flow):
            return (1 - model.f[flow]) + model.f["f17"] >= 1
        
        cr_flow = ["f13", "f14", "f15"]
        for flow in cr_flow:
            model.continuous_to_batch.add(cr_rule(model, flow))
        
        return model
    
    def solve(self, solver_name: str = "gurobi", tee: bool = False):
        """
        Solve the optimization model.
        
        Parameters
        ----------
        solver_name : str, optional
            Name of the solver to use. Default is "gurobi".
        tee : bool, optional
            Whether to print solver output. Default is False.
            
        Returns
        -------
        pyomo.opt.SolverResults
            Solver results object.
        """
        solver = pyo.SolverFactory(solver_name)
        result = solver.solve(self.model, tee=tee)
            
        return result
    
    def get_solution(self) -> Dict:
        """
        Get the solution from the solved model.
        
        Returns
        -------
        dict
            Dictionary containing the solution values.
        """
        if not hasattr(self.model, 'f'):
            raise ValueError("Model has not been solved yet.")
        
        solution = {}
        for flow in self.model.flows:
            solution[flow] = pyo.value(self.model.f[flow])
        
        return solution
    
    def get_objective_value(self) -> float:
        """
        Get the objective function value.
        
        Returns
        -------
        float
            Objective function value.
        """
        return pyo.value(self.model.capex)


class FlowsheetOptimizer:
    """
    High-level interface for flowsheet optimization with iterative process of adding integer cuts to find all feasible solutions.
    """
    
    def __init__(self, file_path: str, sim_data_path: Optional[str] = None):
        """
        Initialize the FlowsheetOptimizer.
        
        Parameters
        ----------
        file_path : str
            Path to the CSV file containing flowsheet data.
        sim_data_path : str, optional
            Path to the simulation data CSV file.
        """
        self.file_path = file_path
        self.sim_data_path = sim_data_path
        self.pyomo_model = PyomoModel(file_path)
        self.results = []
        self.iterations = 0
        self.solve_time_sum = 0
        
        # Load simulation data if provided
        if sim_data_path:
            self.summary_data = read_sim_data(sim_data_path)
        else:
            self.summary_data = None
    
    def solve_iteratively(self, max_iterations: int = 36, solver_name: str = "gurobi", tee: bool = False, save: bool = True, json_filename: str = None) -> pd.DataFrame:
        """
        Solve the optimization problem iteratively with integer cuts.
        
        Parameters
        ----------
        max_iterations : int, optional
            Maximum number of iterations. Default is 36.
        solver_name : str, optional
            Name of the solver to use. Default is "gurobi".
        tee : bool, optional
            Whether to print solver output. Default is False.
        save : bool, optional
            Whether to save results to JSON. Default is True.
        json_filename : str, optional
            Filename for the JSON output. If None, generates a timestamped filename.
        Returns
        -------
        pandas.DataFrame
            DataFrame containing the results of all iterations.
        """
        model = self.pyomo_model.model
        
        # Create ConstraintList for integer cuts
        model.int_cuts = pyo.ConstraintList()
               
        # Dictionary to store unified data for JSON export
        result_dict = {}
        
        for iteration in range(max_iterations):
            self.iterations += 1
            
            # Solve the model
            result = self.pyomo_model.solve(solver_name=solver_name, tee=tee)
            
            # Extract solve time and add to running total
            try:
                solve_time = float(result["Solver"][0]["Wall time"])
                if solve_time is not None:
                    self.solve_time_sum += float(solve_time)
                else:
                    solve_time = None
                    print("Warning: Solve time not available")
            except (KeyError, IndexError, TypeError, ValueError) as e:
                solve_time = None
                print(f"Warning: Could not extract solve time: {e}")

            # Get solution
            solution = self.pyomo_model.get_solution()
            
            # Initialize iteration entry and add flow information directly
            result_dict[self.iterations] = {}
            for flow, value in solution.items():
                result_dict[self.iterations][flow] = value
            
            # Extract operating modes
            operating_modes = self._extract_operating_modes(solution)
            
            # Extract termination condition with error handling
            try:
                termination_condition = result["Solver"][0]["Termination condition"]
            except (KeyError, IndexError, TypeError):
                termination_condition = "Unknown"
                print("Warning: Could not extract termination condition")
            
            # Add results information directly to result_dict
            result_dict[self.iterations].update({
                'operating_modes': operating_modes,
                'solve_time': solve_time,
                'ip_obj_value': self.pyomo_model.get_objective_value(),
                'termination_condition': termination_condition
            })
            
            # Add simulation data if available
            if self.summary_data is not None:
                operating_modes_str = " ".join(operating_modes)
                matching_data = self.summary_data.loc[
                    self.summary_data["Combination"].apply(lambda x: x == operating_modes_str)
                ]
                
                if not matching_data.empty:
                    result_dict[self.iterations].update({
                        'sm_obj_value': float(matching_data["Best Objective Value"].iloc[0]),
                        'sm_eval_time': int(matching_data["Evaluation Time"].iloc[0]),
                        'sm_capex': float(matching_data["Total_CAPEX"].iloc[0])
                    })

            print(f"Iteration {self.iterations} - Configuration: {operating_modes}")
            print(f"Objective function value: {self.pyomo_model.get_objective_value()}")
            print(f"Termination condition: {termination_condition}")
            if solve_time is not None:
                print(f"Solve time: {solve_time:.4f} seconds")
                print(f"Total solve time so far: {self.solve_time_sum:.4f} seconds")
            else:
                print("Solve time: Not available")
                print(f"Total solve time so far: {self.solve_time_sum:.4f} seconds")
            
            # Add integer cut based on the current solution
            self._add_integer_cut(model, solution)
            print(f"Integer cut {self.iterations} added")
            print("-" * 80)
        
        # Save results to CSV if requested
        if save and result_dict:
            if json_filename is None:
                from datetime import datetime
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                json_filename = f"flowsheet_optimization_results_{timestamp}.json"
            
            # Save as JSON
            with open(json_filename, 'w') as f:
                json.dump(result_dict, f, indent=2)
            print(f"Solutions saved to JSON: {json_filename}")
            print(f"JSON contains {len(result_dict)} iterations with combined flow and results information")
        
        return result_dict
    
    def _extract_operating_modes(self, solution: Dict) -> List[str]:
        """
        Extract operating modes from the solution.
        
        Parameters
        ----------
        solution : dict
            Solution dictionary.
            
        Returns
        -------
        list
            List of operating modes.
        """
        operating_modes = []
        uo_keys = self.pyomo_model.data[4]  # uo_keys is the 5th element
        
        for flow, value in solution.items():
            if flow in uo_keys and value == 1:
                operating_modes.append(uo_keys[flow])
        
        return operating_modes
    
    def _add_integer_cut(self, model: pyo.ConcreteModel, solution: Dict):
        """
        Add integer cut based on the current solution.
        
        Parameters
        ----------
        model : pyomo.environ.ConcreteModel
            The Pyomo model.
        solution : dict
            Current solution.
        """
        cut_expr = 0
        flow_with_uo = self.pyomo_model.data[3]  # flow_with_uo is the 4th element
        
        for flow, value in solution.items():
            if flow in flow_with_uo:
                if value < 0.5:
                    cut_expr += model.f[flow]
                else:
                    cut_expr += 1 - model.f[flow]
        
        model.int_cuts.add(cut_expr >= 1)

def get_default_paths():
    """
    Get default file paths for the flowsheet optimization.
    
    Returns
    -------
    tuple
        (flowsheet_data_path, simulation_data_path) as Path objects
    """
    # Get the directory where this script is located
    script_dir = Path(__file__).parent
    
    # Define default file paths relative to the script directory
    flowsheet_data = script_dir / "data" / "ssopt_gen_1.csv"
    simulation_data = script_dir.parent / "simulation" / "data" / "obj_mass_prod_crys" / "run_objmassprodcrys_sum.csv"
    
    return flowsheet_data, simulation_data


def main(flowsheet_data_path: Optional[str] = None, 
         simulation_data_path: Optional[str] = None,
         max_iterations: int = 36,
         solver_name: str = "gurobi",
         tee: bool = False,
         save: bool = True,
         json_filename: str = None):
    """
    Main function demonstrating the usage of the merged flowsheet optimizer.
    
    Parameters
    ----------
    flowsheet_data_path : str, optional
        Path to the flowsheet data CSV file. The file should be located in the data folder, 
        outlining flow, nodes (to, from), cost, and associated unit operations. 
        If None, uses default path.
    simulation_data_path : str, optional
        Path to the simulation data CSV file. If None, uses default path.
    max_iterations : int, optional
        Maximum number of iterations for the optimization. Default is 36.
    solver_name : str, optional
        Name of the solver to use. Default is "gurobi".
    tee : bool, optional
        Option to print solver output. Default is False.
    save : bool, optional
        Whether to save results to JSON. Default is True.
    json_filename : str, optional
        Filename for the JSON output. If None, generates a timestamped filename.
    """
    # Get default paths if not provided
    if flowsheet_data_path is None:
        flowsheet_data_path, _ = get_default_paths()
        flowsheet_data_path = str(flowsheet_data_path)
    
    if simulation_data_path is None:
        _, simulation_data_path = get_default_paths()
        simulation_data_path = str(simulation_data_path)
    
    # Check if files exist and provide helpful error messages
    if not Path(flowsheet_data_path).exists():
        print(f"Warning: Flowsheet data file not found at {flowsheet_data_path}")
        print("Please ensure the data file exists or update the path.")
        return None
    
    if simulation_data_path and not Path(simulation_data_path).exists():
        print(f"Warning: Simulation data file not found at {simulation_data_path}")
        print("Continuing without simulation data...")
        simulation_data_path = None
    
    try:
        # Initialize optimizer
        optimizer = FlowsheetOptimizer(flowsheet_data_path, simulation_data_path)
        
        # Solve iteratively
        results = optimizer.solve_iteratively(
            max_iterations=max_iterations,
            solver_name=solver_name,
            tee=tee,
            save=save,
            json_filename=json_filename
        )
        
        # Print summary
        print(f"\nOptimization completed in {optimizer.iterations} iterations")
        print(f"Total solve time: {optimizer.solve_time_sum:.3f} seconds")
                
        # Export model
        # export_to_mps(optimizer.pyomo_model.model)
        
        return results
        
    except FileNotFoundError as e:
        print(f"File not found: {e}")
        print("Please ensure the data files exist in the correct paths.")
        print(f"Expected flowsheet data at: {flowsheet_data_path}")
        if simulation_data_path:
            print(f"Expected simulation data at: {simulation_data_path}")
    except Exception as e:
        print(f"An error occurred: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    # Run the optimization once, gurobi returns the global optimal solution
    # main(max_iterations=1,tee=True, save=False) 

    main(max_iterations=3, tee=True, save=True) 

    